### ISSUE TITLE
omegaconf.errors.ConfigAttributeError: Missing key logger

### ISSUE THREAD

**Issue by maliho0803** [wzhouxiff/RestoreFormer#2]
Working with z of shape (1, 256, 16, 16) = 65536 dimensions.
loaded pretrained LPIPS loss from /data/juicefs_ai_camera_jgroup/11148646/loss/vgg.pth
VQLPIPSWithDiscriminatorWithCompWithIdentity running with hinge loss.
Traceback (most recent call last):
  File "main.py", line 495, in <module>
    logger_cfg = lightning_config.logger or OmegaConf.create()
  File "/opt/conda/envs/faceformer/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 358, in __getattr__
    key=key, value=None, cause=e, type_override=ConfigAttributeError
  File "/opt/conda/envs/faceformer/lib/python3.7/site-packages/omegaconf/base.py", line 237, in _format_and_raise
    type_override=type_override,
  File "/opt/conda/envs/faceformer/lib/python3.7/site-packages/omegaconf/_utils.py", line 873, in format_and_raise
    _raise(ex, cause)
  File "/opt/conda/envs/faceformer/lib/python3.7/site-packages/omegaconf/_utils.py", line 771, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
  File "/opt/conda/envs/faceformer/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 354, in __getattr__
    key=key, default_value=_DEFAULT_MARKER_, validate_key=False
  File "/opt/conda/envs/faceformer/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 445, in _get_impl
    key=key, throw_on_missing_key=True, validate_key=validate_key
  File "/opt/conda/envs/faceformer/lib/python3.7/site-packages/omegaconf/basecontainer.py", line 78, in _get_child
    throw_on_missing_key=throw_on_missing_key,
  File "/opt/conda/envs/faceformer/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 482, in _get_node
    raise ConfigKeyError(f"Missing key {key!s}")
omegaconf.errors.ConfigAttributeError: Missing key logger
    full_key: logger
    object_type=dict

**Comment by wzhouxiff** [comment]
Maybe it is the different version of omegaconf that leads to the error.

![image](https://user-images.githubusercontent.com/19488619/172302042-75bc8b91-e667-4ebd-84cc-6f30d97d47d8.png)
