### ISSUE TITLE
When run the main.py after setting 'HQ_Dictionary' to ‘conf_name’ in scripts/run.sh.I get an error: Missing key comp_weight

### ISSUE THREAD

**Issue by wizaaaard** [wzhouxiff/RestoreFormer#5]
Hello, I appreciate your work very much, but I have encountered some problems. As the title says, I set  **'HQ_Dictionary'** to **‘conf_name’** in **scripts/run.sh**  before I using **sh scripts/run.sh** command, prepare for training. But I got the following error message:

**_Traceback (most recent call last):
  File "main.py", line 481, in <module>
    model = instantiate_from_config(config.model)
  File "main.py", line 160, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "/opt/data/private/DESKTOPforG/face_restoration/RestoreFormer/RestoreFormer-main/RestoreFormer/models/vqgan_v1.py", line 30, in __init__
    if lossconfig['params']['comp_weight'] or lossconfig['params']['comp_style_weight']:
  File "/root/faceRESTORATION/anaconda3/envs/RestoreFormer/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 377, in __getitem__
    self._format_and_raise(key=key, value=None, cause=e)
  File "/root/faceRESTORATION/anaconda3/envs/RestoreFormer/lib/python3.7/site-packages/omegaconf/base.py", line 237, in _format_and_raise
    type_override=type_override,
  File "/root/faceRESTORATION/anaconda3/envs/RestoreFormer/lib/python3.7/site-packages/omegaconf/_utils.py", line 873, in format_and_raise
    _raise(ex, cause)
  File "/root/faceRESTORATION/anaconda3/envs/RestoreFormer/lib/python3.7/site-packages/omegaconf/_utils.py", line 771, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
  File "/root/faceRESTORATION/anaconda3/envs/RestoreFormer/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 371, in __getitem__
    return self._get_impl(key=key, default_value=_DEFAULT_MARKER_)
  File "/root/faceRESTORATION/anaconda3/envs/RestoreFormer/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 445, in _get_impl
    key=key, throw_on_missing_key=True, validate_key=validate_key
  File "/root/faceRESTORATION/anaconda3/envs/RestoreFormer/lib/python3.7/site-packages/omegaconf/basecontainer.py", line 78, in _get_child
    throw_on_missing_key=throw_on_missing_key,
  File "/root/faceRESTORATION/anaconda3/envs/RestoreFormer/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 482, in _get_node
    raise ConfigKeyError(f"Missing key {key!s}")
omegaconf.errors.ConfigKeyError: Missing key comp_weight
    full_key: model.params.lossconfig.params.comp_weight
    object_type=dict_**

I checked the code carefully and found that the problem lies in your **_RestoreFormer.models.vqgan_v1_**, in the **_RestoreFormerModel_** class of this file, the statement on line 30 is "**_if lossconfig['params']['comp_weight'] or lossconfig['params']['comp_style_weight']:_**". It is this statement that reports an error, because in **_HQ_ Dictionary.yaml_** file, I found that the  **_lossconfig['params']['comp_weight']_** key does not exist exactly. Is this my use error or your project file error. I'm a beginner. Thank you very much. If you can reply and answer my questions, thank you again.

**Comment by wzhouxiff** [comment]
Thanks for you reminder, I have modified Line 13 of vqgan_v1.py to make it compatible to the situation that there is no comp_weight and comp_style_weight in the configure file.
